### ISSUE TITLE
Exclude item or library from results

### ISSUE THREAD

**Issue by mikec61** [custom-components/sensor.plex_recently_added#55] opened 2021-03-04 01:20 UTC
Would there be an ability to exclude certain directories from the sensor data.  For example, my wife records several soap operas on the dvr during the day and these pop up on my HA window in addition to the ones that I request in my Library.  I would like to exclude her library from the display in the sensor.  Going through all of her titles would be labor intensive and wouldn't stop any new ones from appearing.  If I could exclude like the titles exclude feature, that would solve the problem.

**Comment by maykar** [comment] 2021-03-04 11:41
This can either be solved by using the exclude_keywords option or this is a duplicate of #46

**Closed as completed by maykar** 2021-03-04 11:41 UTC
Labels: enhancement

**Comment by mikec61** [comment] 2021-03-04 15:44
My apologies.  I must've missed the other feature request.  Another reason not to post when tired.
