### ISSUE TITLE
Images do not show for Movies. But they do show for TV Shows.

### ISSUE THREAD

**Issue by Adam-North** [custom-components/sensor.plex_recently_added#37] opened 2020-04-20 07:07 UTC
**Describe the Bug**
Images are not being downloaded to the "upcoming-media-card\images\plex" directory. the browser still tries to load the resource and gets a 404 error.

**The Error**
Copy and paste the full error from Home Assistant

No Error.

**Indicate if you followed all steps in the [troubleshooting doc](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md)**
Well, did you?

Doesn't really apply since the components work.

**What data does the sensor display if any?**
Feel free to censor information pertaining to titles, networks, etc.

All the correct data

**What displays when visiting the API URL from the troubleshooting guide?**
Feel free to censor information pertaining to titles, networks, etc.

XML file

**Does the default Home Assistant Plex component work for you?**
This is important to know, helps rule out issues with your Plex installation.

yes

**Home Assistant Version**
What version of HA are you running?

0.108.5

**Additional Context**
![image](https://user-images.githubusercontent.com/16639794/79723206-f97d2180-82aa-11ea-98ef-99d8fb669cef.png)

![image](https://user-images.githubusercontent.com/16639794/79723513-83c58580-82ab-11ea-9a60-fd5c9192a211.png)

-   platform: plex_recently_added
    name: Recently Added Movies
    token: !secret plex_api_key
    host: 10.40.67.25
    port: 32400
    section_types:
    - movie
    
-   platform: plex_recently_added
    name: Recently Added Shows
    token: !secret plex_api_key
    host: 10.40.67.25
    port: 32400
    section_types:
    - show

**Comment by Jopsahl** [comment] 2020-04-21 15:10
I am experiencing the same thing. Some images load, but may disappear. 

If I monitor the image directory I see interesting actions:
Images will download then be removed - This happens for both movies and Television, but the movie images don't seem to re-download or stay loaded. This happens every 30 seconds. 


![Capture](https://user-images.githubusercontent.com/21147777/79881804-4ea65980-83b7-11ea-8c41-6ad2bf924b5a.PNG)

Edit: I gave up and set download_images to false. This solved the problem for me.

**Comment by maykar** [comment] 2020-04-21 20:51
duplicate of https://github.com/custom-components/sensor.plex_recently_added/issues/34

Will be fixed in next release

**Closed as completed by maykar** 2020-04-21 20:51 UTC
